services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/mytheresa:cached
      - /var/www/mytheresa/vendor
    ports:
      - "9000:9000"
    networks:
      - mytheresa_network
    depends_on:
      - database
    entrypoint: [ "/bin/sh", "entrypoint.sh" ]
    command: [ "php-fpm" ]
    environment:
      APP_ENV: dev

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/mytheresa:cached
      - /var/www/mytheresa/vendor
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - mytheresa_network

  database:
    image: mysql:8.0
    env_file:
      - .env
    ports:
      - "3308:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - mytheresa_network

networks:
  mytheresa_network:
    driver: bridge

volumes:
  db-data:
